# Check Pull Requests
# See also: .github/workflows/scripts

name: PR Check and Report

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - closed

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate checkbox # See pull_request_template.md
        uses: roryq/checkmate@master

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-:

      - name: Setup Requirements
        run: |
          pip install -r scripts/requirements.txt

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          json: true
          write_output_files: true
          since_last_remote_commit: true

      - name: Check and Report
        run: |
          python .github/workflows/scripts/check.py
        env:
          # scripts
          github_api_token: ${{ secrets.GITHUB_TOKEN }}
          EVENT_TYPE: ${{ github.event.action }}
          IS_MERGED: ${{ github.event.pull_request.merged }}

          # gh_cli
          PR_NUMBER: ${{ github.event.number }}
